spring.application.name=edi-poc

# Kafka Cluster Location
spring.kafka.bootstrap-servers=localhost:9092

# Producer Serialization Settings
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Optional: Ensure Spring creates the topic if it doesn't exist
spring.kafka.admin.auto-create=true

# Consumer Settings
spring.kafka.consumer.group-id=fulfillment-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

# Tell Spring to trust your domain package when converting JSON back to Java
spring.kafka.consumer.properties.spring.json.trusted.packages=*